name: SonarQube Scan and Build JAR

on:
  # Trigger analysis when pushing to the main branch.
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        architecture: x64
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        overwrite-settings: true
        job-status: success

    - name: Delete SonarQube cache
      run: |
        if (Test-Path $HOME\.sonar) {
          Remove-Item -Path $HOME\.sonar -Force -Recurse
        }
      shell: pwsh

    - name: Change to repository root
      run: cd $GITHUB_WORKSPACE

    - name: Compile Java code and create JAR
      run: |
         # Compile your Java code
         javac HelloWorld.java
         # Create a JAR file
         jar cfe HelloWorld.jar HelloWorld HelloWorld.class

    - name: Save JAR as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld-JAR  # Name of the artifact
        path: HelloWorld.jar  # Path to the JAR file
