name: SonarQube-Scan and Build JAR

on:
  # Trigger analysis when pushing to the main branch.
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        architecture: x64

    - name: Delete SonarQube cache
      run: |
        if [ -d $HOME/.sonar ]; then
          rm -rf $HOME/.sonar
        fi

    - name: SonarQube Scan
      run: |
        # Download and unzip SonarScanner 5
        curl -sSL "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.0.2966-linux.zip" -o sonar-scanner.zip
        unzip sonar-scanner.zip -d .

        # Configure SonarScanner properties (adjust as needed)
        echo "sonar.host.url=${{ secrets.SONAR_HOST_URL }}" >> sonar-scanner-5.0.0.2966-linux/conf/sonar-scanner.properties
        echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-scanner-5.0.0.2966-linux/conf/sonar-scanner.properties
        echo "sonar.projectKey=test" >> sonar-scanner-5.0.0.2966-linux/conf/sonar-scanner.properties

        # Run SonarScanner
        ./sonar-scanner-5.0.0.2966-linux/bin/sonar-scanner

    - name: Change to repository root
      run: cd $GITHUB_WORKSPACE

    - name: Compile Java code and create JAR
      run: |
         # Compile your Java code
         javac HelloWorld.java
         # Create a JAR file
         jar cfe HelloWorld.jar HelloWorld HelloWorld.class

    - name: Save JAR as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld-JAR  # Name of the artifact
        path: HelloWorld.jar  # Path to the JAR file

    - name: Download JAR from SonarQube
      run: |
        # Replace with the actual URL of the JAR file provided by SonarQube
        curl -sSL -o sonarqube.jar "https://9c41-183-82-1-156.ngrok-free.app/dashboard?id=test"
      # Optionally, you can rename the downloaded JAR file if needed
